#include <AffdexException.h>
#include <CameraDetector.h>
#include <Detector.h>
#include <Face.h>
#include <FaceListener.h>
#include <Frame.h>
#include <ImageListener.h>
#include <PhotoDetector.h>
#include <ProcessStatusListener.h>
#include <typedefs.h>
#include <VideoDetector.h>